// Generated by gencpp from file srv_func_package/add_intResponse.msg
// DO NOT EDIT!


#ifndef SRV_FUNC_PACKAGE_MESSAGE_ADD_INTRESPONSE_H
#define SRV_FUNC_PACKAGE_MESSAGE_ADD_INTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srv_func_package
{
template <class ContainerAllocator>
struct add_intResponse_
{
  typedef add_intResponse_<ContainerAllocator> Type;

  add_intResponse_()
    : sum(0)  {
    }
  add_intResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int32_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::srv_func_package::add_intResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srv_func_package::add_intResponse_<ContainerAllocator> const> ConstPtr;

}; // struct add_intResponse_

typedef ::srv_func_package::add_intResponse_<std::allocator<void> > add_intResponse;

typedef boost::shared_ptr< ::srv_func_package::add_intResponse > add_intResponsePtr;
typedef boost::shared_ptr< ::srv_func_package::add_intResponse const> add_intResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srv_func_package::add_intResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srv_func_package::add_intResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srv_func_package::add_intResponse_<ContainerAllocator1> & lhs, const ::srv_func_package::add_intResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srv_func_package::add_intResponse_<ContainerAllocator1> & lhs, const ::srv_func_package::add_intResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srv_func_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srv_func_package::add_intResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srv_func_package::add_intResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv_func_package::add_intResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv_func_package::add_intResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_func_package::add_intResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_func_package::add_intResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srv_func_package::add_intResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba699c25c9418c0366f3595c0c8e8ec";
  }

  static const char* value(const ::srv_func_package::add_intResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba699c25c9418c0ULL;
  static const uint64_t static_value2 = 0x366f3595c0c8e8ecULL;
};

template<class ContainerAllocator>
struct DataType< ::srv_func_package::add_intResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srv_func_package/add_intResponse";
  }

  static const char* value(const ::srv_func_package::add_intResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srv_func_package::add_intResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 sum\n"
;
  }

  static const char* value(const ::srv_func_package::add_intResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srv_func_package::add_intResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct add_intResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srv_func_package::add_intResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srv_func_package::add_intResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRV_FUNC_PACKAGE_MESSAGE_ADD_INTRESPONSE_H
