// Generated by gencpp from file srv_func_package/add_int.msg
// DO NOT EDIT!


#ifndef SRV_FUNC_PACKAGE_MESSAGE_ADD_INT_H
#define SRV_FUNC_PACKAGE_MESSAGE_ADD_INT_H

#include <ros/service_traits.h>


#include <srv_func_package/add_intRequest.h>
#include <srv_func_package/add_intResponse.h>


namespace srv_func_package
{

struct add_int
{

typedef add_intRequest Request;
typedef add_intResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add_int
} // namespace srv_func_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srv_func_package::add_int > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::srv_func_package::add_int&) { return value(); }
};

template<>
struct DataType< ::srv_func_package::add_int > {
  static const char* value()
  {
    return "srv_func_package/add_int";
  }

  static const char* value(const ::srv_func_package::add_int&) { return value(); }
};


// service_traits::MD5Sum< ::srv_func_package::add_intRequest> should match
// service_traits::MD5Sum< ::srv_func_package::add_int >
template<>
struct MD5Sum< ::srv_func_package::add_intRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srv_func_package::add_int >::value();
  }
  static const char* value(const ::srv_func_package::add_intRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_func_package::add_intRequest> should match
// service_traits::DataType< ::srv_func_package::add_int >
template<>
struct DataType< ::srv_func_package::add_intRequest>
{
  static const char* value()
  {
    return DataType< ::srv_func_package::add_int >::value();
  }
  static const char* value(const ::srv_func_package::add_intRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srv_func_package::add_intResponse> should match
// service_traits::MD5Sum< ::srv_func_package::add_int >
template<>
struct MD5Sum< ::srv_func_package::add_intResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srv_func_package::add_int >::value();
  }
  static const char* value(const ::srv_func_package::add_intResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_func_package::add_intResponse> should match
// service_traits::DataType< ::srv_func_package::add_int >
template<>
struct DataType< ::srv_func_package::add_intResponse>
{
  static const char* value()
  {
    return DataType< ::srv_func_package::add_int >::value();
  }
  static const char* value(const ::srv_func_package::add_intResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRV_FUNC_PACKAGE_MESSAGE_ADD_INT_H
