// Generated by gencpp from file srv_func_package/AddInts.msg
// DO NOT EDIT!


#ifndef SRV_FUNC_PACKAGE_MESSAGE_ADDINTS_H
#define SRV_FUNC_PACKAGE_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <srv_func_package/AddIntsRequest.h>
#include <srv_func_package/AddIntsResponse.h>


namespace srv_func_package
{

struct AddInts
{

typedef AddIntsRequest Request;
typedef AddIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddInts
} // namespace srv_func_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srv_func_package::AddInts > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::srv_func_package::AddInts&) { return value(); }
};

template<>
struct DataType< ::srv_func_package::AddInts > {
  static const char* value()
  {
    return "srv_func_package/AddInts";
  }

  static const char* value(const ::srv_func_package::AddInts&) { return value(); }
};


// service_traits::MD5Sum< ::srv_func_package::AddIntsRequest> should match
// service_traits::MD5Sum< ::srv_func_package::AddInts >
template<>
struct MD5Sum< ::srv_func_package::AddIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srv_func_package::AddInts >::value();
  }
  static const char* value(const ::srv_func_package::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_func_package::AddIntsRequest> should match
// service_traits::DataType< ::srv_func_package::AddInts >
template<>
struct DataType< ::srv_func_package::AddIntsRequest>
{
  static const char* value()
  {
    return DataType< ::srv_func_package::AddInts >::value();
  }
  static const char* value(const ::srv_func_package::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srv_func_package::AddIntsResponse> should match
// service_traits::MD5Sum< ::srv_func_package::AddInts >
template<>
struct MD5Sum< ::srv_func_package::AddIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srv_func_package::AddInts >::value();
  }
  static const char* value(const ::srv_func_package::AddIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_func_package::AddIntsResponse> should match
// service_traits::DataType< ::srv_func_package::AddInts >
template<>
struct DataType< ::srv_func_package::AddIntsResponse>
{
  static const char* value()
  {
    return DataType< ::srv_func_package::AddInts >::value();
  }
  static const char* value(const ::srv_func_package::AddIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRV_FUNC_PACKAGE_MESSAGE_ADDINTS_H
